Manishearth/triomphe

- .github/workflows/tests.yml
- Cargo.toml
- lib.rs
This builds on top of #3, as the implementation of `offset_of!` in this crate exhibits miri-detected UB.
The tests in this crate aren't very comprehensive, but with these changes miri no longer complains when running them.
> Fix miri-detected undefined behaviour

- src/header.rs
Note that HeaderWithLength::new function is public, so we already can
muck with the length field:
use triomphe::{HeaderWithLength, ThinArc, Arc};
fn main() {
let thin_arc = ThinArc::from_header_and_iter((), std::iter::once(92));
let mut arc = Arc::from_thin(thin_arc);
Arc::get_mut(&mut arc).unwrap().header = HeaderWithLength::new((), 2);
let thin_arc = Arc::into_thin(arc);
eprintln!("{:?}", &thin_arc.slice);
}
This is not UB because there are necessary runtime assertions to make
sure that the length is correct.
Having access to the length field would allow clients to do thin->thick
transforms themselves, which might be used to, eg, extrac a thin
reference out of ThinArc
> Expose direct access to length

- Cargo.lock
- Cargo.toml
- src/arc.rs
- src/arc_borrow.rs
- src/lib.rs
- src/offset_arc.rs
- src/unique_arc.rs
This provides a patch to unsizing some of the pointers of this crate.
The missing cases would require adjustments to offsetting. (Which is
implemented by casting from `*const T` to `*const u8` which causes a
loss of the associated fat pointer tag if any exists.) They may be added 
later.
Fixes: #9
> Implement unsize crate's trait CoerciblePtr

- src/arc.rs
- src/arc_borrow.rs
- src/offset_arc.rs
- src/thin_arc.rs
- src/unique_arc.rs
* Adds `Arc::try_unwrap()` to attempt converting an `Arc` into an owned value, only succeeds in the case that the ref count is 1
* Adds `Arc::count()` to allow users to see the ref count
* Adds `UniqueArc::into_inner()` to allow converting a `UniqueArc` into an owned value
* Adds `Arc::try_unique()` to attempt converting an `Arc` into a `UniqueArc`
* Adds a `TryFrom<Arc<T>>` implementation for `UniqueArc`
* Removes some implicit `Sized` bounds from `UniqueArc` traits & methods
Closes #20 and #14
> Add Arc::try_unwrap(), Arc::count() and UniqueArc::into_inner()

- .github/workflows/tests.yml
- src/header.rs
- src/thin_arc.rs
Under Stacked Borrows it is very dangerous to create an intermediate reference in unsafe code. In this case, because provenance does not round-trip through a pointer. The pointer you get out only have provenance over the referent, which is often much less than the original pointer.
One can notice that there is a problem here by running `MIRIFLAGS="-Zmiri-tag-raw-pointers" cargo miri test`. The existing diagnostics are pretty vague, but I'm improving them exactly for situations like this. With my changes and tracking the tag with a problem, one sees:
```
test thin_arc::tests::empty_thin ... note: tracking was triggered
--> src/header.rs:68:19
|
68  |             ptr = fake_slice as *mut [T] as *mut ArcInner<HeaderSlice<H, [T]>>;
|                   ^^^^^^^^^^ created tag 206118, granting …
```
> Avoid narrowing provenance through a reference

- Cargo.lock
- src/arc.rs
- src/arc_swap_support.rs
- src/header.rs
- src/thin_arc.rs
Fixes https://github.com/Manishearth/triomphe/issues/38
The root cause of these changes is the same: we need to avoid round-tripping pointers through a reference to the Arc's `T` so that we can use said pointer to access the metadata/reference count.
I also apologize for not catching these earlier. I have a whole dashboard of crates that don't pass Miri and I should have noticed that even after you released 0.1.6 that triomphe still appeared through the dependent crate mentioned in #38.
> Fix provenance issues in as_ptr and new_uninit_slice

- src/arc.rs
- src/unique_arc.rs
Previously `write` would write even to a shared `Arc` which caused UB, as demonstrated by the `maybeuninit_ub_to_proceed` test.
This PR makes `write` panic on non-unique `Arc`s and adds similar functionality to `UniqueArc` where it's always safe.
Fixes #41
> Fix UB in `Arc::<MaybeUninit<_>>::write`

- .github/workflows/tests.yml
`-Zmiri-tag-raw-pointers` no longer has any effect on current versions of Miri; it is enabled by default.
> remove old Miri flags

- src/arc.rs
- src/header.rs
This PR adds the following function:
```rust
impl<H> Arc<HeaderSlice<H, str>> {
pub fn from_header_and_str(header: H, string: &str) -> Self;
}
```
(I've also removed some `T: Sized` bounds from methods, because I've noticed they are useless)
> `Arc::from_header_and_str`

- src/arc.rs
- src/unique_arc.rs
This is almost identical to #42
> Fix unsoundness in `Arc::as_mut_slice`

- src/arc.rs
- src/header.rs
- src/unique_arc.rs
This implements most of the #12.
Missing impls:
- `From<&CStr>`, `From<CString>`, `From<&OsStr>`, `From<OsString>`, `From<&Path>`, `From<PathBuf>` (all these types are quite opaque, so I'm not sure how to work with them)
- `From<Arc<W>> for {Raw,}Waker` (`Wake` trait uses `std::sync::Arc` so there is no reason to implement these impls)
> Implement `From<...>` for `Arc`

- src/header.rs
The warning was:
```
warning: unused return value of `Box::<T>::from_raw` that must be used
--> src/header.rs:238:13
|
238 |             Box::<ManuallyDrop<T>>::from_raw(src as _);
|             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|
= note: call `drop(from_raw(ptr))` if you intend to drop the `Box`
= note: `#[warn(unused_must_use)]` on by default
```
> Mute warning

- src/arc.rs
- src/iterator_as_exact_size_iterator.rs
- src/lib.rs
- src/unique_arc.rs
(Also `UniqueArc::from_iter`.)
Fixes #55.
> Arc::from_iter

- src/arc.rs
- src/unique_arc.rs
I noticed this from warnings about “unclosed HTML tags” when building docs locally. This resulted in docs like [this](https://docs.rs/triomphe/0.1.9/triomphe/struct.Arc.html#method.from_raw) being rendered with `Arc` instead of `Arc<T>` ([source](https://docs.rs/triomphe/0.1.9/src/triomphe/arc.rs.html#74-79)).
> Fix accidental html tags in docs using `Arc<T>` with generic argument

- src/lib.rs
> Fix a typo in lib.rs

- .editorconfig
- LICENSE-APACHE
- README.md
Contributors will have their IDE-s set up automatically.
Includes fixes!
[`eclint`](https://github.com/greut/eclint) can validate all files in a second. It is a single binary.
> Introduce EditorConfig

- src/arc.rs
- src/arc_borrow.rs
- src/unique_arc.rs
As described above, I added safety sections to the docs and fixed the clippy warnings.
> Add safety sections, fix clippy warnings

- Cargo.toml
Doing a version bump as per https://github.com/Manishearth/triomphe/pull/58#issuecomment-1826082098.
> chore: bump to 0.1.9

- Cargo.toml
- src/thin_arc.rs
Remove length check from `ThinSlice::clone`. This check doubles the size of the function generated code. Since `ThinSlice::clone` is inlined everywhere this can improve codegen significantly.
Includes a commit bumping the version to 0.1.10.
Asm before
```asm
.cfi_startproc
sub rsp, 56
.cfi_def_cfa_offset 64
mov rax, qword ptr [rdi]
mov rcx, qword ptr [rax + 8]
lock inc        qword ptr [rax]
jle .LBB366_3
mov qword ptr [rsp], rcx
cmp qword ptr [rax + 8], rcx
jne .LBB366_4
add rsp, 56
.cfi_def_cfa_offset 8
ret
.LBB366_3:
.cfi_def_cfa_offset 64
call qword ptr [rip + std::process::abort@GOTPCREL]
ud2
.LBB366_4:
lea rcx, [rip + .L__unnamed_289]
mov qword ptr [rsp + 8], rcx
mov qword ptr [rsp + 16], 1
mov qword ptr [rsp + 24], 0
lea rcx, [rip + .L__unnamed_183]
mov qword ptr [rsp + 40], rcx …
```
> Remove length check from ThinSlice::clone to halve generated code

- src/arc_borrow.rs
> Lift the `T: 'static` bound from `ArcBorrow::with_arc`

- src/arc.rs
- src/arc_borrow.rs
- src/arc_union.rs
- src/offset_arc.rs
This PR also had to remove the `ArcBorrow::from_ref` API since it was unconditionally unsound to ever use.
Further breakage is in the former `Send`/`Sync` implementation, as this fixes #66
Fixes #65.
This PR supersedes #64. Sorry for the long delay 😅
> Fix arc borrow provenance of, and add a test that actually uses `ArcBorrow`

- src/unique_arc.rs
> Relax the requirements for `Send`/`Sync` implementations of `UniqueArc`

- src/arc.rs
- src/arc_borrow.rs
- src/arc_union.rs
- src/offset_arc.rs
- src/thin_arc.rs
API similar to `std::sync::Arc`.
`ArcBorrow::strong_count` is made to take `&Self` rather than `Self` for consistency with `ArcBorrow::ptr_eq`, although I think by value might be more appropriate. Maybe change everything in version 0.2?
> *::strong_count

- src/arc.rs
- This is what `std::sync::Arc` does
https://github.com/rust-lang/rust/blob/38104f3a8838f8662ad3cccc4d7262a96bf9724e/library/alloc/src/sync.rs#L1841-L1843
- This is behavior change
- Previous behavior was unreliable because compiler could merge/duplicate vtables
- Doing mostly to reduce the number of compiler warnings
- New code requires Rust >= 1.76.0
> Use ptr::addr_eq instead of == in Arc::ptr_eq

- src/header.rs
When exact size iterator is not empty, `.next()` is called twice after iteration ends, and the second call is allowed to return `Some` for non-fused iterator.
Also less code, and probably faster because fewer branches and smaller binary size.
> Simplify/fix Arc::from_iter

- src/arc.rs
If `T` is not `Eq`, we cannot use pointer comparison properly.
But removing pointer comparison kills performance, maybe it is for the best.
> Document PartialEq for Arc bug

- src/arc.rs
- src/lib.rs
`ptr.byte_sub` is stable since 1.75.0.
The tricky part here is figuring out offset of `ArcInner.data` for DST.  This PR assumes that raw pointer is coming from existing `Arc` so it is safe to convert to reference. I'm not 100% sure this is always correct.
Correct version would require `Layout::for_value_raw` (or `mem::align_of_val_raw`) which is not stable.
This can be used to convert `Arc<String>` to `Arc<dyn Debug>`.
> Remove sized requirement from Arc::from_raw

- src/header.rs
We (apollo-compiler) have an AST where most nodes are wrapped in, approximately:
```rust
struct Node<T>(triomphe::Arc<(SourceSpan, T)>);
```
`Arc` allows subtrees to be shared without deep cloning, and `Arc::make_mut` is used extensively for mutability with clone-on-write semantics.
Now I would like to also support `Node<str>` and rely on `Arc::from_header_and_str` for the unsafe bits. This requires using `HeaderSlice` which with triomphe v0.1.12 breaks `Arc::make_mut` because it does not implement `Clone`. This PR fixes that.
`Clone` cannot work for `T: !Sized` which is the main use case for `HeaderSlice` but that’s ok, `derive` automatically insert the appropriate `where` bound. This is still useful in order to have the same `Node<T>` use `HeaderSlice` to support both `T: Sized` and `T: …
> Derive Copy and Clone HeaderSlice and HeaderWithLength

- src/unique_arc.rs
It allows data to be read directly into what will become a ThinArc.
> Add UniqueArc::from_header_and_uninit_slice

- src/arc.rs
`let _ = ...`  is a wildcard binding and as such may not perform a read (I'm not 100% sure on the internal semantics here, but using an actual binding avoids the question)
> Make the actual read happen in UB tests

- .github/workflows/tests.yml
- Cargo.toml
- src/arc.rs
- src/lib.rs
This adds a feature to enable the unstable `dropck_eyepatch` feature and use `may_dangle` on `Arc::drop`, which promises we do not access the inner `T` value (as it may have already been dropped) for users to have more linenant borrow checking behaviour around dropping.
`std::sync::Arc` has this attribute, so lacking this blocks migrating from the `std` Arc to `triomphe`.
> Add may_dangle to Arc::drop conditionally

- src/header.rs
- src/thin_arc.rs
- src/unique_arc.rs
Fixes #107
The breakage is limited to `with_mut()`, which now returns a `HeaderSliceWithLengthChecked` which has an immutable header.
Not fully happy with the resultant API, worth cleaning up in the next major release.
> Seprate HeaderSliceWithLength into checked and unchecked variants

- src/header.rs
- src/thin_arc.rs
- src/unique_arc.rs
This also changes the `ptr:` field of `ThinArc` back to be a non-`…Protected` type. And that's good, because it used `[T; 0]` so the invariantes used to be deliberately broken.
```rust
ptr: ptr::NonNull<ArcInner<HeaderSlice<HeaderWithLength<H>, [T; 0]>>>
```
After this, I also looked through all uses of `ptr` and reworked a few of them (for instance, many of them directly passed the pointer to `thin_to_thick`; which is now part of `thin_to_thick` itself.
> Make `HeaderSliceWithLen…` always contain slices

- src/arc.rs
As discussed in #113 , we want to change the `load acq` to explict `fence acq` to guarantee the memory fence.
This behavior also matches to the std in Rust.
For details, please check:
1. https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2015/n4455.html
2. https://github.com/rust-lang/rust/pull/41714
> Change the acq load to explict acq fence for #113
